apiVersion: v2
name: polardb-storage-resizer
description: PolarDB Storage Resizer
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/maskshell/polardb-storage-resizer
sources:
  - https://github.com/maskshell/polardb-storage-resizer
maintainers:
  - name: maskshell
