{{/*
PolarDB Storage Resizer - ServiceAccount Template
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "polardb-resizer.serviceAccountName" . }}
  namespace: {{ include "polardb-resizer.namespace" . }}
  labels:
    {{- include "polardb-resizer.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "polardb-resizer.rrsaAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
